### ISSUE TITLE
ASCII color in Windows 7 SP1

### ISSUE THREAD

**Issue by thefirefox12537** [kiedtl/winfetch#87] opened 2021-06-20 01:06 UTC
I use Windows 7 SP1 and installed Windows PowerShell 5.1 (Windows Modules Framework). ASCII color it does not show this. Any have solutions?

**Comment by rashil2000** [comment] 2021-06-20 03:24
Did you have a look at the Readme?

Also, this is a duplicate of #82, please search for related problems here before opening a new issue.

**Closed** 2021-06-20 03:24 UTC
