### ISSUE TITLE
Winfetch No Longer Working on Windows 11

### ISSUE THREAD

**Issue by g33k247** [kiedtl/winfetch#136] opened 2022-05-07 01:17 UTC
As of 5/6/22, winfetch has stopped working on my Windows 11 machine. When I attempt to run it as normal, the script throws errors. Any help in resolving these errors is appreciated.

----------------------------------------------
Invoke-WebRequest "https://raw.githubusercontent.com/kiedtl/winfetch/master/winfetch.ps1" -UseBasicParsing | Invoke-Expression
Invoke-Expression : At line:68 char:1
+ [CmdletBinding()]
+ ~~~~~~~~~~~~~~~~~
Unexpected attribute 'CmdletBinding'.
At line:69 char:1
+ param(
+ ~~~~~
Unexpected token 'param' in expression or statement.
At line:80 char:75
+ ... eSet("text", "bar", "textbar", "bartext")][string]$cpustyle = "text",
+                                                                   ~~~~~~
The assignment expression is not valid. The input to an assignment operator must be an object that is able to accept
assignments, such as a variable or a property.
At line:81 char:78
+ ... t("text", "bar", "textbar", "bartext")][string]$memorystyle = "text",
+                                                                   ~~~~~~
The assignment expression is not valid. The input to an assignment operator must be an object that is able to accept
assignments, such as a variable or a property.
At line:82 char:76
+ ... Set("text", "bar", "textbar", "bartext")][string]$diskstyle = "text",
+                                                                   ~~~~~~
The assignment expression is not valid. The input to an assignment operator must be an object that is able to accept
assignments, such as a variable or a property.
At line:83 char:79
+ ... ("text", "bar", "textbar", "bartext")][string]$batterystyle = "text",
+                                                                   ~~~~~~
The assignment expression is not valid. The input to an assignment operator must be an object that is able to accept
assignments, such as a variable or a property.
At line:84 char:108
+ ...  $Host.UI.RawUI.WindowSize.Width-1})][alias('w')][int]$imgwidth = 35,
+                                                                       ~~
The assignment expression is not valid. The input to an assignment operator must be an object that is able to accept
assignments, such as a variable or a property.
At line:85 char:25
+     [array]$showdisks = @($env:SystemDrive),
+                         ~~~~~~~~~~~~~~~~~~~
The assignment expression is not valid. The input to an assignment operator must be an object that is able to accept
assignments, such as a variable or a property.
At line:1 char:110
+ ... tl/winfetch/master/winfetch.ps1" -UseBasicParsing | Invoke-Expression
+                                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : UnexpectedAttribute,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by rashil2000** [comment] 2022-05-07 13:35
The script was recently changed to "UTF-8 with BOM" instead of "UTF-8" encoding, which caused the above error. Any ideas @astelmachonak-nydig?

**Comment by astelmachonak-nydig** [comment] 2022-05-07 13:38
Let me try to reproduce this on my Windows 11 machine, however this is strange.

**Comment by VincentJoshuaET** [comment] 2022-05-08 12:01
This happens to me with this command:

`Invoke-WebRequest "https://raw.githubusercontent.com/kiedtl/winfetch/master/winfetch.ps1" -UseBasicParsing | Invoke-Expression`

But if I download the file first, it works properly.

**Comment by astelmachonak-nydig** [comment] 2022-05-09 15:40
Issue is not Windows 11 specific and reproducible on Windows 10 as well in case 

```
Invoke-WebRequest "https://raw.githubusercontent.com/kiedtl/winfetch/master/winfetch.ps1" -UseBasicParsing | Invoke-Expression
```

command is used. In this case file is not saved on disk and Powershell 5 doesn't recognize it as UTF-8. Any other options with saving file locally before execution work fine.

Looking for the solution - ideas how to force UTF-8 for execution are welcome.

**Comment by astelmachonak-nydig** [comment] 2022-05-09 16:38
I did some more research. Basically this issue is caused by `Invoke-WebRequest` and `Invoke-Expression` commands inability to properly process UTF-8 witb BOM on-the-fly (see https://github.com/PowerShell/PowerShell/issues/11547). When content is stored to the file, this doesn't matter, however when request body passed to `Invoke-Expression` as-is, is can't be processed properly.

Honestly I don't see a good solution here. As of version 2.4.1, running winfetch without saving to file is broken for both Powershell 5 and 7. If we revert BOM fix (like it was in 2.4.0), we will make winfetch broken for Powershell 5 (without system-level workaround). Should be revisit the MS Logo to exclude UTF-8 symbols? It won't look fancy, but will work everywhere.

**Comment by astelmachonak-nydig** [comment] 2022-05-09 18:14
@rashil2000 nice workaround! This is something I was looking for! Regarding upstream issue - it will never be fixed in Powershell 5, so we will need to accept it as permanent solution while winfetch supports this version of Powershell :)

**Comment by astelmachonak-nydig** [comment] 2022-05-09 20:06
@rashil2000 are you going to open PR to update the README page?

**Comment by rashil2000** [comment] 2022-05-09 20:32
I didn't get it, why do we need to update the Readme?

**Comment by astelmachonak-nydig** [comment] 2022-05-09 20:36
Yes, at the bottom of this page: https://github.com/kiedtl/winfetch/wiki/Installation 
I think this is where users get this command from

**Comment by rashil2000** [comment] 2022-05-09 20:37
Updated: https://github.com/kiedtl/winfetch/wiki/Installation/_compare/a38eb5d64f784a9433df3128d0642ed7d3dd77be

**Closed by rashil2000** 2022-05-09 20:37 UTC
